<?php

/**
 * @file
 * Geocoder plugin using the ESRI geocoding service
 */


/**
 * Implements hook_ctools_plugin_api().
 */
function esri_geocoder_ctools_plugin_api() {
  return array('version' => 1);
}

/**
 * Implements hook_ctools_plugin_dierctory().
 */
function esri_geocoder_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_ctools_plugin_type().
 */
function esri_geocoder_ctools_plugin_type() {
  return array(
    'geocoder_handler' => array(),
  );
}
